/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.Carhistory;
import model.Car;

/**
 *
 * @author rishi
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
    Carhistory obj;
    public MainJframe() {
        initComponents();
        obj= new Carhistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Splitpane = new javax.swing.JSplitPane();
        controlarea = new javax.swing.JPanel();
        addcar_btn = new javax.swing.JButton();
        viewcar_btn = new javax.swing.JButton();
        viewarea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlarea.setBackground(new java.awt.Color(204, 204, 204));

        addcar_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addcar_btn.setText("Add Car");
        addcar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcar_btnActionPerformed(evt);
            }
        });

        viewcar_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        viewcar_btn.setText("View Car");
        viewcar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlareaLayout = new javax.swing.GroupLayout(controlarea);
        controlarea.setLayout(controlareaLayout);
        controlareaLayout.setHorizontalGroup(
            controlareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addcar_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlareaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewcar_btn)
                .addContainerGap())
        );
        controlareaLayout.setVerticalGroup(
            controlareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlareaLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(addcar_btn)
                .addGap(18, 18, 18)
                .addComponent(viewcar_btn)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        Splitpane.setLeftComponent(controlarea);

        viewarea.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout viewareaLayout = new javax.swing.GroupLayout(viewarea);
        viewarea.setLayout(viewareaLayout);
        viewareaLayout.setHorizontalGroup(
            viewareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        viewareaLayout.setVerticalGroup(
            viewareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        Splitpane.setRightComponent(viewarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Splitpane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Splitpane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addcar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcar_btnActionPerformed
    AddJPanel j =new AddJPanel(obj);
     Splitpane.setRightComponent(j);
     
        // TODO add your handling code here:
    }//GEN-LAST:event_addcar_btnActionPerformed

    private void viewcar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcar_btnActionPerformed
       ViewJPanel v =new ViewJPanel(obj);
     Splitpane.setRightComponent(v); // TODO add your handling code here:
     
      
    }//GEN-LAST:event_viewcar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane Splitpane;
    private javax.swing.JButton addcar_btn;
    private javax.swing.JPanel controlarea;
    private javax.swing.JPanel viewarea;
    private javax.swing.JButton viewcar_btn;
    // End of variables declaration//GEN-END:variables
}
